### ISSUE TITLE
Test Fails for Node.js >= 12

### ISSUE THREAD

**Issue by nileshpatra** [gruntjs/grunt-legacy-util#27]
Hi, the tests fail with the following error for Node.js >= 12:
```
[master][~/ups/grunt-legacy-util]$ npm run test
(node:22763) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

> grunt-legacy-util@1.1.1 test /home/nilesh/ups/grunt-legacy-util
> grunt test

Running "jshint:all" (jshint) task
>> 3 files lint free.

Running "nodeunit:util" (nodeunit) task
Testing index.js......(node:22777) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
.............F.........
>> util.spawn.multibyte - partial stdout
>> Error: 'こんにちは(node:22887) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.' == 'こんにちは'
>> at /home/nilesh/ups/grunt-legacy-util/test/index.js:300:12
>> at callDone (index.js:160:5)
>> at ChildProcess.<anonymous> (index.js:199:5)
>> at ChildProcess.emit (events.js:210:5)
>> at ChildProcess.EventEmitter.emit (domain.js:475:20)
>> at maybeClose (internal/child_process.js:1021:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

Warning: 1/98 assertions failed (2468ms) Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! grunt-legacy-util@1.1.1 test: `grunt test`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the grunt-legacy-util@1.1.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nilesh/.npm/_logs/2020-01-24T19_25_04_713Z-debug.log
```

It would be great if they could be fixed soon. Thanks!

**Comment by nileshpatra** [comment]
Looks like the deprecations in stdout were the cause of errors.
Doing 
`export NODE_NO_WARNINGS=1`

Fixes it!
