### ISSUE TITLE
runInContext causing issues on CentOS

### ISSUE THREAD

**Issue by beliaev-maksim** [gruntjs/grunt-legacy-util#29]
On CentOS the code is failing. Stupid solution is just to catch an error and in case switch to:
`var _ = util._ = require('lodash')`

Here is a full error
```
error: Grunt :: /home/git/release_server/node_modules/grunt-legacy-util/index.js:26
var _ = util._ = require('lodash').runInContext();
                                   ^

TypeError: require(...).runInContext is not a function
    at Object.<anonymous> (/home/git/release_server/node_modules/grunt-legacy-util/index.js:26:36)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/git/release_server/node_modules/grunt/lib/grunt.js:35:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

```

@jdalton @vladikoff 
can you please review?

**Comment by drw026** [comment]
I managed to fix this by using the old version of lodash. I think they have removed the function in their new release.

**Comment by vladikoff** [comment]
The function is still in here: https://lodash.com/docs/4.17.15#runInContext in the docs. I wonder what happened to that

**Comment by drw026** [comment]
In their new release 4.17.18 which was today. It is maybe removed. https://www.npmjs.com/package/lodash

**Comment by vladikoff** [comment]
@drw026 see https://github.com/lodash/lodash/issues/4845 They are fixing it there for now, reopen this in case we can do something in this module to fix this up

**Comment by beliaev-maksim** [comment]
@drw026 , @vladikoff 
thank you both!
it is a great luck that they fixed it that soon :)

do you think we need to update package.json so specify exact versions or we can leave it?

**Comment by drw026** [comment]
You can leave it. It will automatically get the newer version of lodash.

**Comment by beliaev-maksim** [comment]
ok, thank you all!
at least we have everything documented and visible here :)
